package com.mckinsey.jenkins.GithubPipelineCreator.github.events;

public enum GitHubEvent {

    COMMIT_COMMENT, CREATE, DELETE, DEPLOYMENT, DEPLOYMENT_STATUS, FORK, GOLLUM, ISSUE_COMMENT, ISSUES, MEMBER, MEMBERSHIP, PAGE_BUILD, PUBLIC, PULL_REQUEST_REVIEW_COMMENT, PULL_REQUEST, PUSH, REPOSITORY, RELEASE, STATUS, TEAM_ADD, WATCH
}
